# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prntenv < Formula
  desc "Utility to print out the names and values of the variables in the environment"
  homepage "https://github.com/jcouture/prntenv"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jcouture/prntenv/releases/download/0.1.1/prntenv_0.1.1_darwin_amd64.tar.gz"
      sha256 "1b4f473c213cb0a4eeb9a91ec088723c11e6a85425403d5709df1be32e45c688"

      def install
        bin.install "prntenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jcouture/prntenv/releases/download/0.1.1/prntenv_0.1.1_darwin_arm64.tar.gz"
      sha256 "e5cb1a12ac5e106122f41ca13213921f1d46252eb9d062937450acacd93685aa"

      def install
        bin.install "prntenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jcouture/prntenv/releases/download/0.1.1/prntenv_0.1.1_linux_armv6.tar.gz"
      sha256 "c9589d06ad242f63b8f2885bedfd483c10906f6d93f16024f7b1cf15c00ced16"

      def install
        bin.install "prntenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jcouture/prntenv/releases/download/0.1.1/prntenv_0.1.1_linux_arm64.tar.gz"
      sha256 "c660e9c5a5581424b35368ce33fbc575d4392b0f09c469580d87a2441f3e905c"

      def install
        bin.install "prntenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jcouture/prntenv/releases/download/0.1.1/prntenv_0.1.1_linux_amd64.tar.gz"
      sha256 "dd5a0d64f228e0524cfa0b0e1350bf951a51e502c33b513294fb8e402e049b99"

      def install
        bin.install "prntenv"
      end
    end
  end

  test do
    system "#{bin}/prntenv"
  end
end
